spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: create